config/routes.rb
Rails.application.routes.draw do

  get 'followers/index'

  get 'following/index'

  devise_for :users
  resources :images do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    resources :followers, only: [:index]
    resources :following, only: [:index]
  end

  resources :relationships, only: [:create, :destroy]
  resources :newsfeed, only: :index
  resources :search, only: :index

  unauthenticated  do
    root "static_pages#show", act: "home"
  end

  authenticated  do
    root "home#index"
  end
  get "/pages/:act" => "static_pages#show"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images = Image.all.order(id: :desc).page params[:page]
  end
end

app/views/home/_create.html.erb
<div class="create-post">
  <div class="row">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">投稿を作成</h3>
      </div>
      <div class="panel-body">
        <%= form_for :image, url: images_path, html: { multipart: true }  do |f| %>
          <div class="col-sm-9">
            <div class="form-group">
              <img src="<%= current_user.avatar.thumb.url %>" alt="" class="profile-photo-md"/>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.text_area :body, placeholder: "今何している？", class: "form-control", cols:"60", rows:"1", required: true %>

            </div>
            <hr>
            <div class="col-sm-10 col-sm-offset-1">
              <%= f.file_field :file, placeholder: "Image", required: true %>
            </div>

          </div>
          <div class="col-sm-3">
            <button class="btn btn-primary pull-right btn-sm" type="submit">投稿する</button>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/home/_left.html.erb
<div class="col-sm-3 static" id="static">
  <div id="sidebar">
    <br>
    <div class="profile-card">
      <img src="<%= current_user.avatar.thumb.url %>" alt="user" class="profile-photo"/>
      <h5>
        <%= link_to current_user.username, current_user, class: "text-white" %>
      </h5>
      <%= link_to user_followers_path(current_user), class: "text-white" do %>
        <b><%= current_user.followers.count %> </b>  followers
      <% end %>
      <br>
      <%= link_to user_following_index_path(current_user), class: "text-white" do %>
        <b><%= current_user.following.count %></b>  following
      <% end %>
    </div><!--profile card ends-->
    <ul class="nav-news-feed">
      <li><i class="fa fa-newspaper-o"></i>
        <div><a href="<%= root_path %>">ホーム</a></div>
      </li>
      <li><i class="fa fa fa-picture-o"></i>
        <div><%= link_to "ニュースフィード", newsfeed_index_path %></div>
      </li>
      <li><i class="fa fa fa-clock-o"></i>
        <div><%= link_to "タイムライン", current_user %></div>
      </li>
      <li><i class="fa fa fa-users"></i>
        <div><%= link_to "Followers", user_followers_path(current_user)%></div>
      </li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<br>
<div class="container">
  <div class="row">
    <%= render "home/left" %>
    <div class="col-sm-7">
      <%= render "home/create" %>
      <div class="media">
        <div class="row js-masonry" data-masonry='{ "itemSelector": ".grid-item", "percentPosition": true }'>
          <% @images.each do |image| %>
            <div class="grid-item col-md-6 col-sm-6">
              <div class="media-grid">
                <%= link_to image do %>
                  <div class="img-wrapper">
                      <img src="<%= image.file.thumb.url %>" alt=""
                           class="img-responsive post-image"/>
                  </div>
                <% end %>
                <div class="media-info">
                  <div class="reaction">
                    <a class="btn <% if current_user.like_image? image  %> text-green <% end %>"><i class="fa fa-thumbs-up"></i> <%= image.likes.count %></a>
                    <span class="pull-right" style="padding-top: 5px"><%= time_ago_in_words(image.created_at) %> ago</span>
                  </div>
                  <div class="user-info">
                    <img src="<%= image.user.avatar.thumb.url %>" alt=""
                         class="profile-photo-sm pull-left"/>
                    <div class="user">
                      <h6>
                        <%= link_to image.user.username, image.user, class: "profile-link" %>
                      </h6>
                      <a class="text-green" href="#">Friend</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <hr>
      <%= paginate @images,theme: 'twitter-bootstrap-3' %>
    </div>
  </div>
</div>