config/routes.rb
Rails.application.routes.draw do

  get 'followers/index'

  get 'following/index'

  devise_for :users
  resources :images do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    resources :followers, only: [:index]
    resources :following, only: [:index]
  end

  resources :relationships, only: [:create, :destroy]
  resources :newsfeed, only: :index
  resources :search, only: :index

  unauthenticated  do
    root "static_pages#show", act: "home"
  end

  authenticated  do
    root "home#index"
  end
  get "/pages/:act" => "static_pages#show"


end

app/models/image.rb
class Image < ApplicationRecord
  paginates_per 10

  belongs_to :user

  has_many :likes
  has_many :comments

  mount_uploader :file, ImageUploader
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [:show, :edit, :update, :destroy]

  def create
    image = Image.new new_image_params
    if image.save
      flash[:success] = "画像がアップロードされました"
      redirect_to image
    else
      flash[:error] = "Error when create image"
      redirect_back
    end
  end

  def show
    @comments = @image.comments.page params[:page]
  end

  def edit

  end

  def update
    if @image.update_attributes update_image_params
      flash[:success] = "画像が破壊されました"
      redirect_to @image
    else
      flash[:error] = "イメージは破壊できません"
      redirect_back
    end
  end

  def destroy
    if @image.destroy
      flash[:success] = "画像が破壊されました"
      redirect_to root_path
    else
      flash[:error] = "イメージは破壊できません"
      redirect_back
    end
  end

  protected
  def new_image_params
    params.require(:image).permit :user_id, :file, :body
  end

  def update_image_params
    params.require(:image).permit :user_id, :file, :body
  end

  def find_image
    @image = Image.find_by id: params[:id]
    unless @image
      flash[:error] = "写真がありません"
      redirect_to root_path
    end
  end
end

app/views/images/edit.html.erb
<br>
<div class="container">
  <div class="row">
    <%= render "home/left" %>
    <div class="col-sm-7">
      <h3 class="text-center">画像を編集する</h3>
      <hr>
      <%= form_for @image, html: { multipart: true } do |f| %>
        <div class="col-sm-9">
          <div class="form-group">
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.text_area :body, placeholder: "あなたが望むものを書く", class: "form-control", cols:"60", rows:"1", required: true, value: @image.body %>
          </div>
            <%= f.file_field :file, placeholder: "Image" %>
            <br>
          <img src="<%= @image.file.url %>" alt="" class="img-responsive center-block" style="border: 2px solid gray; border-radius: 5px;">
        </div>
        <div class="col-sm-3">
          <button class="btn btn-primary btn-sm btn-block" type="submit">アップデイト</button>
          <hr>
          <%= link_to "キャンセル", @image, class: "btn btn-danger btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/images/show.html.erb
<br>
<div class="container">
  <div class="row">
    <%= render "home/left" %>
    <div class="col-sm-7">
      <!-- Post Content
            ================================================= -->
      <% if user_signed_in? %>
        <% if current_user.id == @image.user.id  %>
          <h3>
            <%= link_to edit_image_path(@image), class: "pull-right", "data-toggle": "tooltip",
                title: "画像を編集する", "data-placement": "bottom" do %>
              <i class="fa fa-cog fa-fw"></i>
            <% end %>
            <%= link_to image_path(@image), method: :delete, class: "pull-right",title: "画像を削除する",
                        "data-toggle": "tooltip", "data-placement": "bottom" ,data: {confirm: "確信してるの？"} do %>
              <i class="fa fa-trash fa-fw text-danger"></i>
            <% end %>
          </h3>
        <% end %>
      <% end %>
      <div class="post-content">
        <img src="<%= @image.file.url %>" alt="post-image" class="img-responsive post-image" />
        <div class="post-container">
          <img src="<%= @image.user.avatar.thumb.url %>" alt="user" class="profile-photo-md pull-left" />
          <div class="post-detail">
            <div class="user-info">
              <h5>
                <%= link_to @image.user.username, @image.user, class: "profile-link" %></h5>
              <p class="text-muted"><%= time_ago_in_words(@image.created_at) %> ago 写真を公開しました</p>
            </div>
            <div class="reaction">
              <% if current_user.like_image? @image %>
                <%= link_to image_like_path(@image), class: "btn btn-default text-green", method: :delete do %>
                  <i class="fa fa-thumbs-up"></i> <%= @image.likes.count %>
                <% end %>
              <% else %>
                <%= link_to image_likes_path(@image), class: "btn btn-default", method: :post do %>
                  <i class="fa fa-thumbs-up"></i> <%= @image.likes.count %>
                <% end %>
              <% end %>
            </div>
            <div class="line-divider"></div>
            <div class="post-text">
              <p><%= @image.body %></p>
            </div>
            <div class="line-divider"></div>
            <% @comments.each do |comment| %>
              <div class="post-comment">
                <img src="<%= comment.user.avatar.thumb.url %>" alt="" class="profile-photo-sm" />

                <p>
                  <a href="<%= user_path comment.user %>" class="profile-link"><%= comment.user.username %> </a>
                  <i class="em em-laughing"></i>
                  <%= comment.body %>
                  <br>
                  <small>
                    <%= comment.updated_at %>
                    <% if comment.user_id == current_user.id %> |
                      <%= link_to image_comment_path(@image, comment), method: :delete do %>
                        <i class=" fa fa-trash"></i>
                      <% end %>
                    <% end %>
                  </small>
                </p>

              </div>
            <% end %>
            <hr>
            <%= paginate @comments,theme: 'twitter-bootstrap-3' %>
            <% if user_signed_in? %>
              <%= form_for :comment, url: image_comments_path(@image), id: "comment" do |f| %>
                <div class="post-comment">
                  <img src="<%= current_user.avatar.thumb.url %>" alt="" class="profile-photo-sm" />
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.text_field :body, class: "form-control", placeholder: "コメントを投稿", required: true %>
                </div>
              <% end %>
            <% end %>
            <script type="text/javascript" charset="utf-8">
              jQuery(document).ready(function($) {
                $('#input').keypress(function (event) {
                  if(event.keyCode === 10 || event.keyCode === 13){
                    $('form').submit();
                  }
                });
              });
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>