config/routes.rb
Rails.application.routes.draw do

  get 'followers/index'

  get 'following/index'

  devise_for :users
  resources :images do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show] do
    resources :followers, only: [:index]
    resources :following, only: [:index]
  end

  resources :relationships, only: [:create, :destroy]
  resources :newsfeed, only: :index
  resources :search, only: :index

  unauthenticated  do
    root "static_pages#show", act: "home"
  end

  authenticated  do
    root "home#index"
  end
  get "/pages/:act" => "static_pages#show"


end

app/views/layouts/_footer.html.erb
<footer>
  <div class="splitter"></div>
  <ul>
    <ul>
      <li>
        <div class="icon" data-icon="E"></div>
        <div class="text">
          <h4>私たちに関しては</h4>
          <div>
            チーム名：スゲー <br>
            チームメンバー：<br>
            Nguyen Dat Duy (20130599) GL <br>
            Le Vinh Thien (20133740) SL <br>
            Tran The Vinh (20134628) <br>
            Nguyen The Phuong (20133026) <br>
            Ta Duc Dung (20130699) <br>
            Doi Khac Thanh (20133512 <br>
            <a href="#">Read more</a>
          </div>
        </div>
      </li>
      <li>
        <div class="icon" data-icon="a"></div>
        <div class="text">
          <h4>お問い合わせ</h4>
          <div>ベトナムの有名な観光名所を紹介する「場所」「感情」を確認できる。アカウント登録すると、
            写真をアップロードできるログインすると、自分の写真を削除できるログインすると、
            写真でコメントすることができる <br>
            <a href="#">Read more</a></div>
        </div>
      </li>
      <li>
        <div class="icon" data-icon="s"></div>
        <div class="text">
          <h4>ニュース</h4>
          <div>
            ベトナムの有名な観光名所を紹介する「場所」「感情」を確認できる。アカウント登録すると、
            写真をアップロードできるログインすると、自分の写真を削除できるログインすると、
            写真でコメントすることができる <br>
            <a href="#">Read more</a></div>
        </div>
      </li>
    </ul>
  </ul>
  <div class="bar">
    <div class="bar-wrap">
      <ul class="links"> <!-- footer menu -->
        <li><a href="#">ホーム</a></li>
        <li><a href="#">ライセンス</a></li>
        <li><a href="#">お問い合わせ</a></li>
        <li><a href="#">広告する</a></li>
      </ul>

      <div class="social">
        <a href="#" class="fb">
          <span data-icon="f" class="icon"></span>
          <span class="info">
                    <span class="follow">ファンになるFacebook</span>
                    <span class="num">9,999</span>
                </span>
        </a>

        <a href="#" class="tw">
          <span data-icon="T" class="icon"></span>
          <span class="info">
                    <span class="follow">私たちに従ってください</span>
                    <span class="num">9,999</span>
                </span>
        </a>

        <a href="#" class="rss">
          <span data-icon="R" class="icon"></span>
          <span class="info">
                    <span class="follow">RSSを購読する</span>
                    <span class="num">9,999</span>
                </span>
        </a>
      </div>
      <div class="clear"></div>
      <div class="copyright">Wevivu &copy;  2017 All Rights Reserved</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wevivu", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <% @q = Image.ransack(params[:q]) %>
      <%= search_form_for @q, class:"navbar-form navbar-left", role: "search", url: search_index_path do |f| %>
        <div class="form-group">
          <%= f.search_field :body_cont, class: "form-control", placeholder: "サーチ" %>
        </div>
        <button class="btn btn-default" type="submit">提出する</button>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Wevivuについて", "/pages/about" %></li>
        <% if user_signed_in?  %>
          <li>
            <%= link_to "ホーム", root_path %>
          </li>
          <li>
            <%= link_to "ニュースフィード", newsfeed_index_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
           <%= current_user.username %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to current_user do %>
                  <i class="fa fa-user fa-fw"></i>タイムライン
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-fw fa-cog"></i> プロフィール
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-fw fa-sign-out"></i> ログアウト
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "サインイン", new_user_session_path %></li>
          <li><%= link_to "サインアップ", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wevivu | ベトナムの有名な観光名所</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Baloo" rel="stylesheet">
    <link href="<%= asset_path "favicon.png" %>" rel="shortcut icon" type="image/x-icon" />
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application"%>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="wrapper <% if user_signed_in? %> no-bg <% end %>">
      <%= yield %>
    </div>
    <br>
    <br>
    <%= render "layouts/footer" %>
    <%= render "layouts/message" %>
    <script type="text/javascript" charset="utf-8">
      var preloader = $('#spinner-wrapper');
      $(window).on('load', function() {
        var preloaderFadeOutTime = 2000;

        function hidePreloader() {
          preloader.fadeOut(preloaderFadeOutTime);
        }
        hidePreloader();
      });
    </script>
  </body>
</html>